---
Name: deploynaut-alerts
After:
  - '#deploynaut'
---
DNRoot:
  extensions:
    - DNRootAlertsExtension
  url_handlers:
    'project/$Project/alerts': 'alerts'
DNProject:
  extensions:
    - DNProjectAlertsExtension
